apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.name }}
  labels:
    app.kubernetes.io/name: {{ template "test_mysql.name" . }}
    helm.sh/chart: {{ template "test_mysql.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      nodePort: 30007

  selector:
     app: {{ .Values.name }}
