apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test_kafka.fullname" . }}
  labels:
    {{- include "test_kafka.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
       app: {{ .Values.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "test_kafka.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "test_kafka.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-inside
              containerPort: 9093
            - name: tcp-outside
              containerPort: 9094
          env:
           - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
             value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,LOOPBACK:PLAINTEXT"
           - name: KAFKA_ADVERTISED_LISTENERS
             value: "INSIDE://DEMO_TEST_KAFKA:9093,OUTSIDE://{{ .Values.kafkaOutSideName }}:9094,LOOPBACK://localhost:9095" 
           - name: KAFKA_LISTENERS
             values: "INSIDE://:9093,OUTSIDE://:9093,LOOPBACK://:9095"
           - name: KAFKA_INTER_BROKER_LISTENER_NAME
             value: "LOOPBACK"
           - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
             value: "1"
           - name: KAFKA_LOG_RETENTION_HOURS
             value: "40"
           - name: KAFKA_DELETE_TOPIC_ENABLE
             value: "true"
           - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
             value: "false"
           - name: KAFKA_PORT
             value: "9093"          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
