apiVersion: v1
kind: Service
metadata:
  name: {{ include "test_kafka.name" . }}
  labels:
    {{- include "test_kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.seviceType }}
  ports:
    - name: tcp-inside
      port: 9092
      targetPort: 9092
    - name: tcp-outside
      port: 9094
      targetPort: 9094  
  selector:
     app: {{ .Values.name }}
