apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test_zookeeper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "test_zookeeper.name" . }}
    helm.sh/chart: {{ template "test_zookeeper.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       app: {{ .Values.name }}
       release: {{ .Release.Name}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.clientPort }}
              name: client
            - containerPort: {{ .Values.serverPort }}
              name: server
            - containerPort: {{ .Values.leaderElectionPort }}
              name: leader-election
          volumeMounts:
             - name: data
               mountPath: /opt/zookeeper/data
          env:
            - name:  ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZK_CLIENT_PORT
              value: "{{ .Values.clientPort }}"
            - name: ZK_SERVER_PORT
              value: "{{ .Values.serverPort }}"
            - name: ZK_ELECTION_PORT
              value: "{{ .Values.leaderElectionPort }}"
            - name: Djute.maxbuffer
              value: "0x400000"

            # - name: SERVER_JVMFLAGS
            #  value: "Xmx256m -Xms256m"

          readinessProbe:
              exec:
                command:
                  - "/opt/bitnami/zookeeper/bin/zkServer.sh"
                  - "status"
              periodSeconds: {{ .Values.periodSeconds }}
              timeoutSeconds: {{ .Values.timeoutSeconds}}
              failureThreshold: {{ .Values.failureThreshold}}

          resources:
             requests:
               cpu: 0.1
               memory: 750Mi
             limits:
               cpu: 1
               memory: 750Mi
      volumes:
         - name: data
           emptyDir: {}

       {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

