apiVersion: v1
kind: Service
metadata:
  name: na-zookeeper
  labels:
    app.kubernetes.io/name: {{ template "test_zookeeper.name" . }}
    helm.sh/chart: {{ template "test_zookeeper.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.serverPort }}
      name: server
    - port: {{ .Values.leaderElectionPort }}
      name: leader-election
    - port: {{ .Values.clientPort }}
      name: clientport

  selector:
    app: {{ .Values.name }}
  release: {{ .Release.name }}