# Default values for test_zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  #repository: bitnami/zookeeper
  repository: gshukla123/demo_zookeeper
  pull_policy: always
  tag: v1

serviceType: NodePort
name: demo-zookeeper
serverPort: 2888
leaderElectionPort: 3888
clientPort: 2181
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
periodSeconds: 5
timeoutSeconds: 5
failureThreshold: 10

security:
  enabled: false
  runAsUser: 1000
  fsGroup: 1000



nodeSelector: {}

tolerations: []

affinity: {}
